/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForcePasswordChangeRouteImport } from './routes/force-password-change'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountStatusRouteImport } from './routes/account-status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as FamilyTokenRouteImport } from './routes/family/$token'
import { Route as ApiSseRouteImport } from './routes/api/sse'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcePasswordChangeRoute = ForcePasswordChangeRouteImport.update({
  id: '/force-password-change',
  path: '/force-password-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountStatusRoute = AccountStatusRouteImport.update({
  id: '/account-status',
  path: '/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTokenRoute = FamilyTokenRouteImport.update({
  id: '/family/$token',
  path: '/family/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSseRoute = ApiSseRouteImport.update({
  id: '/api/sse',
  path: '/api/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-status': typeof AccountStatusRoute
  '/admin': typeof AdminRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/super-admin': typeof SuperAdminRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sse': typeof ApiSseRoute
  '/family/$token': typeof FamilyTokenRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-status': typeof AccountStatusRoute
  '/admin': typeof AdminRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/super-admin': typeof SuperAdminRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sse': typeof ApiSseRoute
  '/family/$token': typeof FamilyTokenRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-status': typeof AccountStatusRoute
  '/admin': typeof AdminRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/super-admin': typeof SuperAdminRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sse': typeof ApiSseRoute
  '/family/$token': typeof FamilyTokenRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-status'
    | '/admin'
    | '/force-password-change'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/stats'
    | '/super-admin'
    | '/verify-email'
    | '/api/health'
    | '/api/sse'
    | '/family/$token'
    | '/uploads/$'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-status'
    | '/admin'
    | '/force-password-change'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/stats'
    | '/super-admin'
    | '/verify-email'
    | '/api/health'
    | '/api/sse'
    | '/family/$token'
    | '/uploads/$'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/account-status'
    | '/admin'
    | '/force-password-change'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/stats'
    | '/super-admin'
    | '/verify-email'
    | '/api/health'
    | '/api/sse'
    | '/family/$token'
    | '/uploads/$'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountStatusRoute: typeof AccountStatusRoute
  AdminRoute: typeof AdminRoute
  ForcePasswordChangeRoute: typeof ForcePasswordChangeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  SuperAdminRoute: typeof SuperAdminRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSseRoute: typeof ApiSseRoute
  FamilyTokenRoute: typeof FamilyTokenRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-password-change': {
      id: '/force-password-change'
      path: '/force-password-change'
      fullPath: '/force-password-change'
      preLoaderRoute: typeof ForcePasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-status': {
      id: '/account-status'
      path: '/account-status'
      fullPath: '/account-status'
      preLoaderRoute: typeof AccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/$token': {
      id: '/family/$token'
      path: '/family/$token'
      fullPath: '/family/$token'
      preLoaderRoute: typeof FamilyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sse': {
      id: '/api/sse'
      path: '/api/sse'
      fullPath: '/api/sse'
      preLoaderRoute: typeof ApiSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountStatusRoute: AccountStatusRoute,
  AdminRoute: AdminRoute,
  ForcePasswordChangeRoute: ForcePasswordChangeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  SuperAdminRoute: SuperAdminRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSseRoute: ApiSseRoute,
  FamilyTokenRoute: FamilyTokenRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
